/**:
    ros__parameters:
      box_1:
        width: 0.115
        length: 0.100
        height: 0.075
      box_2:
        width: 0.160
        length: 0.125
        height: 0.075
      box_3:
        width: 0.100
        length: 0.075
        height: 0.075
